connect-foundation/2019-08

client/src/presentation/components/message-card-contents.tsx, client/src/presentation/components/message-card-image.tsx, client/src/presentation/components/message-card.tsx, server/package-lock.json, server/package.json
**issue** -#12
- 독립적인 메세지 컴포넌트를 만들었음
- 차후 다른 코드에서 연결이 필요함
=> Feature message card ui

.github/PULL_REQUEST_TEMPLATE.md
- 공통된 규격으로 pull request 보내도록 설정
- 추가로 필요하거나 수정할 항목이 있으면 코멘트 주세요.
=> pull request format 지정 (#26) Merged By @Gipyoo 

server/jest.config.js, server/package-lock.json, server/package.json, server/src/app.ts, server/src/controllers/apis/channel-api-controller.ts, server/src/entity/Channel.ts, server/src/routes/chnnel-router.ts, server/src/server.ts, server/test/integrate/apis/channel-api-controller.test.ts, server/test/ormconfig.test.ts
>  #31 
- 채널 이름으로 Channel 정보를 조회할 수 있다.
=> 이름 기준으로 채널 조회하는 기능 추가

client/src/App.tsx, client/src/presentation/components/atomic-reusable/custom-button.tsx, client/src/presentation/components/atomic-reusable/custom-drop-down.tsx, client/src/presentation/components/atomic-reusable/custom-modal.tsx, client/src/presentation/components/atomic-reusable/icon-box.tsx, client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-dropdown.tsx, client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-header.tsx, client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-information.tsx, client/src/presentation/components/snug/channel-browse-modal/index.tsx, client/src/presentation/components/snug/channel-list/channel-header.tsx, client/src/presentation/components/snug/channel-list/channel-title.tsx, client/src/presentation/components/snug/channel-list/index.tsx, client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx, client/src/presentation/components/snug/channel-plus-modal/index.tsx, client/src/presentation/components/snug/chat-input-box/index.tsx, client/src/presentation/components/snug/post-card/index.tsx, client/src/presentation/pages/snug/index.tsx, client/src/presentation/pages/snug/message-section/content.tsx, client/src/presentation/pages/snug/message-section/header.tsx, client/src/presentation/pages/snug/message-section/index.tsx, client/src/presentation/pages/snug/sidebar/index.tsx, client/src/presentation/theme/color-theme.ts
>  
테마를 이용하여 상수화 되어있던 컬러 코드들을 테메로 통일 시킴
=> 스타일 컴포넌트 테마를 활용한 전역적 스타일 관리

client/src/presentation/components/atomic-reusable/profile-thumnail.tsx, client/src/presentation/components/snug/chat-container/index.tsx, client/src/presentation/components/snug/post-card/index.tsx, client/src/presentation/components/snug/post-card/post-card-contents.tsx
>  #12 
기존 메세지라는 이름을 가지고 만들어졌던 포스트 카드를 엔티티의 이름과 같이 모든 메세지라는 이름을 post로 변경하고 프롭스의 이름도 그 의미가 더 명확하고 엔티티의 인자들의 이름과 대부분 일치하도록 리팩토링함
=> [Refactor] 포스트카드 리팩토링

client/.env.development, client/src/App.tsx
why : React app에서는 환경변수의 이름이 REACT_APP 으로 시작해야 적용되기 때문에 값을 변경하고, 소켓 서버 주소를 프록시 서버주소와 통일 시킴
=> fix : 잘못되어있는 환경변수 설정을 수정함

.vscode/launch.json, client/.env.development, client/src/App.tsx, client/src/data/http/api/post-api.ts, client/src/data/repository/post-repository.ts, client/src/presentation/components/snug/chat-container/index.tsx, client/src/presentation/components/snug/chat-input-box/index.tsx, server/src/controller/api/post-controller.ts
>  소켓 이벤트가 중복으로 선언되어 메세지 렌더링이 중복적으로 렌더링 되는 현상을 해결함
=> fix : 채팅 렌더링이 중복되는 이슈를 해결함

server/src/controller/api/common/paginator.ts, server/src/entity/Post.ts, server/test/integrate/channel/post/post-controller.test.ts
- Pair Programming With @sangwon21
- Posts 조회시 profile 을 즉시 조회하도록 eager 설정 추가한다
- Paginator Default Size 값이 15 로 변경한다
=> Channel 대한 메시지 목록에 프로필 정보가 포함되지 않는 이슈

server/src/controller/api/post-controller.ts
=> fix: post 생성시 roomId를 저장

client/src/App.tsx, client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-item.tsx, client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-sort-list.tsx, client/src/presentation/components/snug/channel-browse-modal/index.tsx, client/src/presentation/components/snug/chat-container/index.tsx, client/src/presentation/pages/home/home-detail-snug.tsx, client/src/presentation/pages/snug/header/index.tsx, client/src/presentation/pages/snug/message-section/content.tsx
> 전반적인 디자인 채널목록 너비 조정, 채널 목록에 스크롤 추가함
=> Refactor design

client/src/core/service/auth-service.ts, client/src/core/use-case/auth-repository-type.ts, client/src/data/repository/auth-repository.ts, client/src/presentation/components/atomic-reusable/global-header.tsx, client/src/presentation/components/atomic-reusable/page-layout.tsx, client/src/presentation/pages/home/index.tsx, client/src/presentation/pages/register-snug/index.tsx, client/src/presentation/pages/register-user/index.tsx
>  #114 
- 로그아웃 버튼을 누르면 로그아웃이 된다.
- 로그아웃이 되면 헤더가 바뀐다.
=> Feature front logout

client/package-lock.json, client/package.json, client/src/@context/http-providers/http-providers.tsx, client/src/@context/repositories/index.tsx, client/src/@context/services/index.tsx, client/src/@context/storage-providers/storage-providers.tsx, client/src/core/entity/token.ts, client/src/core/entity/user.ts, client/src/core/model/json-web-token-model.ts, client/src/core/service/auth-service.ts, client/src/core/use-case/auth-repository-type.ts, client/src/data/browser-storage/browser-storage-helper.ts, client/src/data/browser-storage/browser-storage-mapper.ts, client/src/data/browser-storage/browser-storage.ts, client/src/data/browser-storage/custom-mapper/json-web-tocken-mapper.ts, client/src/data/http/api/auth-api.ts, client/src/data/http/api/axios-wrapper.ts, client/src/data/http/api/channel-api.ts, client/src/data/repository/auth-repository.ts, client/src/presentation/components/atomic-reusable/custom-login-input.tsx, client/src/presentation/components/atomic-reusable/global-header.tsx, client/src/presentation/components/atomic-reusable/page-layout.tsx, client/src/presentation/pages/home/home-form.tsx, client/src/presentation/pages/home/home-snug.tsx, client/src/presentation/pages/home/index.tsx, client/src/presentation/pages/register-snug/index.tsx, client/src/presentation/pages/register-user/index.tsx, server/src/controller/api/auth-controller.ts, server/src/controller/api/channel-controller.ts
> #105 #106 #107 #108 
- 사용자가 로그인을 할 수 있다.
- 사용자가 로그인에 성공하면 홈 화면으로 바뀐다.
- 사용자가 로그인을 실패하면 폼이 초기화 된다.
- 사용자가 로그인에 성공하면 그 이후 부터 axios 해더에 토큰이 저장 된다.
이 기능들을 구현하게 된 이유는 사용자가 자신의 계정을 가지고 스너그들을 관리하기 위해서 이다.
=> Feature front login

client/src/App.tsx, server/src/controller/api/auth-controller.ts, server/src/controller/api/snug-controller.ts, server/src/model/notifier/invite-notifier.ts
snug 생성 및 리스트 가져올 때 발생하는 버그 픽스 및 text decoration 수정
=> hotfix: snug list 기능 및 text decoration

client/src/presentation/pages/home/home-snug.tsx, server/src/controller/api/auth-controller.ts
#132 
user entity의 email column 변경으로 auth controller에서 user를 제대로 select를 못하는 문제가 발생했습니다. 해결하기 위해 email 객체를 생성해서 조건을 넘겨주어 조회했습니다.
=> 로그인 과정에서 typerom이 User를 제대로 찾지 못하는 문제 수정

client/src/App.tsx, client/src/contexts/path-parameter-context.tsx, client/src/core/entity/path-parameter.ts, client/src/presentation/components/snug/channel-list/channel-title.tsx, client/src/presentation/components/snug/channel-list/index.tsx, client/src/presentation/pages/snug/index.tsx
#136 
pathParameter에 snugId와 channelId 기반으로 동작하도록 기능을 수정했다.
- [ x Bug fix
=> snug 페이지 접근시 url 버그 수정

client/src/core/service/channel-service.ts, client/src/core/use-case/channel-repository-type.ts, client/src/data/http/api/channel-api.ts, client/src/data/repository/channel-repository.ts
why : 사용자가 채널 프리뷰 화면에서 들어가면 채널에 조인할 수 있도록 하기 위하여 -issue:#11
=> feat :  채널에 참여하는  fetch 구현

server/src/controller/api/auth-controller.ts, server/src/controller/api/channel-controller.ts, server/src/routes/channel/channel-router.ts
=> Feature api preview

client/src/App.tsx, client/src/contexts/socket-context.tsx, client/src/presentation/components/invitation-alarm/index.tsx, client/src/presentation/components/snug/channel-list/index.tsx, client/src/presentation/components/snug/chat-container/index.tsx, client/src/presentation/components/snug/chat-input-box/index.tsx, client/src/presentation/pages/home/home-snug.tsx, client/src/presentation/pages/invite-users/container/index.tsx, client/src/presentation/pages/invite-users/form/index.tsx, client/src/presentation/pages/invite-users/index.tsx, client/src/presentation/pages/register-user/index.tsx, client/src/presentation/pages/snug/index.tsx, client/src/presentation/pages/snug/message-section/content.tsx, client/src/presentation/pages/snug/message-section/index.tsx, client/src/presentation/pages/snug/sidebar/index.tsx, client/src/prop-types/match-extends-types.ts
초대 알람과 메세지 알람의 독립적 기능을 구현을 위해 socket의 namespace를 통해 두개의 socket으로 구별했다.
driver: kyungrae
navigator: GiPyoo
=> user socket과 snug 소켓을 분리하여 구현

client/src/core/service/profile-service.ts, client/src/core/use-case/profile-repository-type.ts, client/src/data/http/api/profile-api.ts, client/src/data/repository/profile-repository.ts, client/src/util/cookie.ts, server/src/controller/api/auth-controller.ts, server/src/controller/api/channel-controller.ts
>  #157
쿠키로 내용을 박아오기 때문에 이 내용을 고려하여 기존에 api를 활용하는 방식에서 쿠키를 활용하는 방식으로 변경함
=> Deature profile cookie

server/src/controller/api/auth-controller.ts, server/src/controller/api/common/messages.ts, server/src/controller/api/common/token/profile-token.ts, server/src/domain/entity/Invite.ts, server/src/domain/vo/Email.ts, server/src/domain/vo/Ticket.ts, server/src/migration/1575729716556-ADD-TICKET-TYPE.ts, server/src/migration/1575997516122-ADD-PHONE-AND-CHANGE-USER-JOIN-COLUMN.ts, server/src/migration/1576118484821-ADD-EMAIL-INDEX.ts, server/src/migration/1576118787009-ADD-TICKET-INDEX.ts, server/src/model/profile/profile-info.ts, server/src/template/email-contents.ts
1. Profile Token 항목으로 status, email, description 추가
2. Email, Ticket Index 추가하여 조회시 인덱스를 이용할 수 있도록 엔터티 수정
=> Profile Token 항목으로 status, email, description 추가

client/src/presentation/components/atomic-reusable/icon-box.tsx, client/src/presentation/components/snug/chat-input-box/index.tsx, client/src/presentation/components/snug/file-preview/image-preview.tsx, client/src/presentation/components/snug/file-preview/index.tsx, client/src/presentation/components/snug/file-preview/normal-preview.tsx, client/src/presentation/components/snug/file-upload-modal/file-drop-area.tsx, client/src/presentation/components/snug/file-upload-modal/index.tsx, client/src/presentation/pages/snug/message-section/content.tsx
#139 
파일과 글을 함께 업로드 할 수 있는 UI 기능을 구현했습니다. 
파일 업로드할 때, 파일 형식(이미지 or 텍스트)에 따라 파일 미리보기를 다르게 구현했습니다.
=> 파일을 업로드할 수 있는 UI 기능 구현

server/src/app.ts, server/src/controller/api/participate-in-controller.ts, server/src/routes/participate-in/index.ts, server/src/validator/identifier-validator.ts
>  #159 
내가 참여하고 있는 채널을 불러오는 api 구현
=> Feature api participate

client/src/presentation/pages/snug/index.tsx
=> feat : url을 통해 스너그에 들어 왔을 때 해당하는 채널에 색이 칠이 칠해지도록 기능을 구현함

client/src/data/repository/channel-repository.ts, client/src/presentation/components/snug/chat-input-box/index.tsx, client/src/presentation/pages/snug/index.tsx, server/src/controller/api/channel-controller.ts, server/src/controller/api/participate-in-controller.ts, server/src/controller/api/post-controller.ts
- 프로필을 인식하지 못하는 부분
- 채팅이 안오는 버그
- 관계가 설정되지 않았던 부분 고침
=> fix : 치명적인 오류 해결

client/src/data/repository/channel-repository.ts, client/src/presentation/pages/snug/index.tsx, client/src/presentation/pages/snug/message-section/content.tsx, client/src/presentation/pages/snug/profile/buttons/index.tsx, client/src/presentation/pages/snug/profile/header/index.tsx, client/src/presentation/pages/snug/profile/index.tsx, client/src/presentation/pages/snug/profile/modal/modal-input.tsx, client/src/presentation/pages/snug/profile/status/index.tsx, client/src/presentation/pages/snug/profile/status/status-bar-header.tsx, client/src/presentation/pages/snug/profile/status/status-bar.tsx
why: console.log를 모두 삭제 후, profile UI를 수정했다.
=> fix: profile UI 수정

server/src/controller/api/user-controller.ts, server/src/domain/entity/Invite.ts, server/src/model/invite/invitee.ts
- 회원가입에서 초대장 정보를 모두 조회해, 초대받은 user 정보로 업데이트하는 절차 추가하여 해결
- 회원가입 후 초대받은 정보를 확인할 수 있다.
=> 회원가입에서 초대 정보를 조회하지 못하는 이슈

client/src/contexts/messages-context.tsx, client/src/data/http/api/post-api.ts, client/src/data/repository/post-repository.ts, client/src/presentation/components/snug/chat-container/index.tsx, client/src/presentation/components/snug/post-card/post-card-contents.tsx, client/src/presentation/components/snug/thread-container/index.tsx, client/src/presentation/components/snug/thread-input-box/index.tsx, client/src/presentation/pages/snug/message-section/content.tsx, client/src/presentation/pages/snug/thread/index.tsx, server/src/model/chat/post-info.ts, server/src/model/notifier/chat/chat-notifier.ts, server/src/model/notifier/invite-notifier.ts, server/src/socket/action/invite.ts, server/src/socket/action/snug.ts
Pair Programmed with @raccoonback
=> Fix thread

client/src/contexts/messages-context.tsx, client/src/core/entity/post.tsx, client/src/core/service/post-service.ts, client/src/core/use-case/post-repository-type.ts, client/src/data/http/api/post-api.ts, client/src/data/repository/post-repository.ts, client/src/presentation/components/snug/chat-input-box/index.tsx, client/src/presentation/components/snug/post-card/file-contents.tsx, client/src/presentation/components/snug/post-card/post-card-contents.tsx, server/src/controller/api/post-controller.ts, server/src/model/chat/chatter.ts
- 포스트 카드에 이미지 혹은 파일을 넣을 수 있는 박스 추가
- 메세지 생성시 프로필 id를 넘겨주는 것이아닌 쿠키를 활용하여 프로필 검증
=> 포스트카드 변경 및 메세지 생성시 프로필 매직 넘버 수정

client/src/App.tsx, client/src/presentation/components/snug/chat-container/index.tsx, client/src/presentation/components/snug/chat-input-box/index.tsx, client/src/presentation/components/snug/file-upload-modal/index.tsx, client/src/presentation/components/snug/post-card/file-contents.tsx, client/src/presentation/components/snug/post-card/index.tsx, client/src/presentation/components/snug/post-card/post-card-contents.tsx, client/src/presentation/pages/snug/index.tsx, server/package-lock.json, server/src/controller/api/post-controller.ts, server/src/model/chat/post-info.ts
파일 업로드시 파일을 다운 로드 받을 수 있는 이미지 미리보기와 파일을 준다.
=> 파일이 추가된 포스트 카드

client/src/presentation/components/snug/file-upload-modal/index.tsx, client/src/presentation/components/snug/thread-container/index.tsx, client/src/presentation/pages/snug/thread/header/index.tsx, client/src/presentation/pages/snug/thread/index.tsx
=> Fix thread design

client/src/data/http/api/axios-wrapper.ts, client/src/data/http/api/channel-api.ts, client/src/data/repository/channel-repository.ts, client/src/data/repository/invite-repository.ts, client/src/data/repository/post-repository.ts, client/src/data/repository/profile-repository.ts, client/src/data/repository/snug-repository.ts, client/src/data/repository/user-repository.ts, client/src/presentation/components/atomic-reusable/custom-button.tsx, client/src/presentation/components/atomic-reusable/page-layout.tsx
=> fix: ==와 type assertion을 lint추천대로 수정

client/src/App.tsx, client/src/data/repository/post-repository.ts, client/src/presentation/components/snug/chat-container/index.tsx, client/src/presentation/components/snug/chat-input-box/index.tsx, client/src/presentation/components/snug/post-card/post-card-contents.tsx, client/src/presentation/pages/snug/message-section/content.tsx
why : 사용자가 문단도 채팅으로 사용할 수 있게 하기 위하여
=> fix : 채팅 인풋을 텍스트 에어리어로 변경함

client/src/data/repository/post-repository.ts
=> 파일 업로드 채널 구별

client/src/presentation/pages/home/home-form.tsx, client/src/presentation/pages/home/home-snug.tsx, client/src/presentation/pages/home/modal/index.tsx, client/src/presentation/pages/invite-users/form/invite-users.tsx
why: 사용자가 로그인에 실패했을 때 로그인 안내 메세지로 알려준다.
=> feat: 로그인 실패시 로그인 안내 메시지

client/src/core/service/channel-service.ts, client/src/core/service/user-service.ts, client/src/core/use-case/channel-repository-type.ts, client/src/core/use-case/user-repository-type.ts, client/src/data/http/api/channel-api.ts, client/src/data/http/api/user-api.ts, client/src/data/repository/channel-repository.ts, client/src/data/repository/user-repository.ts, client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx, client/src/presentation/pages/register-user/register-user-form.tsx, server/src/controller/api/channel-controller.ts, server/src/controller/api/common/messages.ts, server/src/controller/api/user-controller.ts, server/src/routes/snug/channel/channel-router.ts, server/src/routes/user/user-router.ts
=> Refact error message popup

client/src/presentation/components/snug/post-card/index.tsx, client/src/presentation/components/snug/post-card/post-card-contents.tsx
- 이미지나 파일을 다운 로드 받았을 때 스레드 창이 나오는 오류해결
- 스레드 카운트 디자인 변경
=> Fix thread event

client/src/presentation/pages/error/index.tsx, client/src/presentation/pages/invite-users/index.tsx, client/src/presentation/pages/register-snug/index.tsx
=> Feat auth client

client/src/App.tsx, client/src/presentation/components/snug/channel-plus-modal/index.tsx, client/src/presentation/pages/snug/auth.tsx, server/src/controller/api/common/messages.ts
서버에서 누락된 메세지 추가, 채널 모달 생성시 발생하는 버그 해결, 에러페이지 렌더링 버그 해결
=> 에러 페이지, 모달, 누라된 메세지 추가

client/src/App.tsx, client/src/contexts/messages-context.tsx, client/src/core/service/post-service.ts, client/src/core/use-case/post-repository-type.ts, client/src/data/http/api/post-api.ts, client/src/data/repository/post-repository.ts, client/src/presentation/components/atomic-reusable/global-header.tsx, client/src/presentation/components/snug/channel-list/channel-title.tsx, client/src/presentation/components/snug/channel-list/side-button.tsx, client/src/presentation/components/snug/chat-container/index.tsx, client/src/presentation/components/snug/chat-input-box/index.tsx, client/src/presentation/pages/home/home-detail-snug.tsx, client/src/presentation/theme/color-theme.ts
- 헤더 스너그 아이콘 변경
- 스너그 리스트 정렬
- 스너그 리스트 이미지 스너그 이미지로 생성
=> Fix snug list & 페이지 네이션

client/src/core/service/channel-service.ts, client/src/core/use-case/channel-repository-type.ts, client/src/data/http/api/channel-api.ts, client/src/data/repository/channel-repository.ts, client/src/presentation/components/atomic-reusable/custom-drop-down.tsx, client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-dropdown.tsx, client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-sort-list.tsx, client/src/presentation/components/snug/channel-browse-modal/index.tsx, client/src/presentation/components/snug/channel-list/index.tsx, server/src/controller/api/channel-controller.ts, server/src/domain/entity/Room.ts, server/src/model/participant/participant.ts, server/src/server.ts
> 상위 컴포넌트인 channel-browse-modal 에서 상태를 내려주도록 변경하여 해결
=> 채널 목록 조회 모달에서 Title, Sort 기준이 적용되지 않는 이슈

client/src/presentation/components/atomic-reusable/custom-drop-down.tsx, client/src/presentation/components/snug/chat-input-box/index.tsx
1. Message Input Box 중앙 정렬되도록 CSS 변경
> With @sangwon21
=> Message Input Box 중앙 정렬되도록 CSS 변경

client/src/contexts/messages-context.tsx, client/src/presentation/components/snug/chat-container/index.tsx, server/src/model/chat/chatter.ts
- 포스츠를 불러오는 과정에서 데이터를 리버스하여 보내주는 것을 없애고 바로 보낸다.
- 클라이언트에서 리버스하여 정렬하는 코드를 추가함
=> Posts Default Reverse 수정

client/package.json
=> fix : change version in pakage.json of client

client/src/core/service/auth-service.ts, client/src/core/use-case/auth-repository-type.ts, client/src/data/http/api/auth-api.ts, client/src/data/repository/auth-repository.ts, client/src/presentation/components/atomic-reusable/global-header.tsx, client/src/presentation/components/snug/chat-container/index.tsx, client/src/presentation/components/snug/thread-input-box/index.tsx, client/src/presentation/pages/home/home-form.tsx, server/src/controller/api/auth-controller.ts, server/src/routes/auth/auth-router.ts, server/src/validator/identifier-validator.ts
- 현재 Thread 에 노출되는 post.id 와 새로운 댓글의 post.id 비교하여 렌더링 여부를 결정하도록 변경
- 채널 입장시 소켓 replyPost 이벤트 구독하는 로직 추가하여 해결
- 로그인된 경우에만 invite-alarm 컴포넌트 노출하도록 변경하여 해결
- Snug 입장하지 않아 Profile 쿠키가 존재하지 않는다
- 따라서 Snug 입장하지 않고 로그아웃할 경우, API 서버의 "Profile 쿠키 존재 여부 검증"하는 미들웨어에서 에러가 발생한다
- "Profile 쿠키 존재 여부 검증" 제거하고, 올바르게 Profile 쿠키를 제거하도록 변경하여 해결
=> 현재 Thread 와 상관없는 reply 와 로그인 화면에 알림 컴포넌트 노출되는 이슈

client/src/presentation/components/atomic-reusable/global-header.tsx, client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-item.tsx, client/src/presentation/components/snug/channel-list/channel-header.tsx, client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx, client/src/presentation/pages/snug/message-section/content.tsx, server/src/controller/api/channel-controller.ts, server/src/model/participant/participant.ts, server/src/routes/snug/channel/channel-router.ts
> 프라이빗 채널 조회시 중복된 퍼블릭 채널 조회가 발생하기 때문에, 함수를 분리하여 오직 프라이빗 채널만 조회하도록 변경하여 해결
=> 채널 목록 조회시 중복된 퍼블릭 채널을 조회하는 이슈
